server:
  port: 80
  servlet:
    context-path: /sb1/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/java20
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
